// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "./match_server/Match.h"
#include "./save_client/Save.h"
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/ThreadFactory.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportUtils.h>
#include <thrift/TToString.h>

#include <iostream>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <queue>
#include <vector>
#include <unistd.h>

using namespace apache::thrift;
using namespace apache::thrift::concurrency;
using namespace apache::thrift::protocol;
using namespace apache::thrift::transport;
using namespace apache::thrift::server;

using namespace ::match_service;
using namespace ::save_service;
using namespace std;


struct Task
{
    User user;
    std::string type;
};

struct MessageQueue
{
    std::queue<Task> q;
    std::mutex m;
    std::condition_variable cv;
}message_queue;


class Pool
{
    public:
        void save_result(int a, int b)
        {
            printf("Match Result: %d %d\n", a, b);

            std::shared_ptr<TTransport> socket(new TSocket("123.57.47.211", 9090));
            std::shared_ptr<TTransport> transport(new TBufferedTransport(socket));
            std::shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
            SaveClient save_client(protocol);

            try {
                transport->open();

                int res = save_client.save_data("acs_395", "83c95896", a, b);

                if ( !res ) puts("success");
                else puts("failed");

                transport->close();
            } catch (TException& tx) {
                std::cout << "ERROR: " << tx.what() << std::endl;
            }
        }

        void match()
        {
            while (users.size() > 1)
            {
                /*
                 sort(users.begin(), users.end(), [&](User &a, User &b){
                        return a.score < b.score;
                        });
                */

                for (uint32_t i = 0; i < wait_times.size(); i++)
                    wait_times[i] ++; //等待秒数 + 1

                bool flag = false;
                for (uint32_t i = 0; i < users.size() - 1; i ++)
                {
                    for (uint32_t j = i + 1; j < users.size(); j ++)
                    {
                        if (check_match(i, j))
                        {
                            auto a = users[i], b = users[j];
                            users.erase(users.begin() + j);
                            users.erase(users.begin() + i);
                            wait_times.erase(wait_times.begin() + j);
                            wait_times.erase(wait_times.begin() + i);

                            save_result(a.id, b.id);

                            flag = true;

                            break;
                        }
                    }

                    if (flag) break;
                }

                if (!flag) break;
            }
        }

        bool check_match(int i, int j)
        {
            auto a = users[i], b = users[j];

            int dt = abs(a.score - b.score); //两个玩家的分值差
            int a_max_dt = wait_times[i] * 50; // a 玩家可接受的最大分值差
            int b_max_dt = wait_times[j] * 50; // b 玩家可接受的最大分值差

            return dt <= a_max_dt && dt <= b_max_dt; // 分值差满足a,b可接受范围内，匹配出给
        }

        void add(User user)
        {
            users.push_back(user);
            wait_times.push_back(0);
        }

        void remove(User user)
        {
            for (uint32_t i = 0; i < users.size(); i ++ )
                if (users[i].id == user.id)
                {
                    users.erase(users.begin() + i);
                    wait_times.erase(wait_times.begin() + i);
                    break;
                }
        }

    private:
        std::vector<User> users;
        std::vector<int> wait_times;
}pool;

void consume_task()
{
    while (true)
    {
        std::unique_lock<std::mutex> lck(message_queue.m);
        if (message_queue.q.empty())
        {
            //message_queue.cv.wait(lck);
            lck.unlock();
            pool.match();
            sleep(1); //sleep 1s
        }
        else
        {
            auto task = message_queue.q.front();
            message_queue.q.pop();
            lck.unlock();

            if (task.type == "add") pool.add(task.user);
            else if (task.type == "remove") pool.remove(task.user);

            //pool.match();
        }
    }
}

class MatchHandler : virtual public MatchIf {
    public:
        MatchHandler() {
            // Your initialization goes here
        }

        int32_t add_user(const User& user, const std::string& info) {
            // Your implementation goes here
            printf("add_user\n");

            std::unique_lock<std::mutex> lck(message_queue.m);
            message_queue.q.push({user, "add"}); //临界区
            message_queue.cv.notify_all();

            return 0;
        }

        int32_t remove_user(const User& user, const std::string& info) {
            // Your implementation goes here
            printf("remove_user\n");

            std::unique_lock<std::mutex> lck(message_queue.m);
            message_queue.q.push({user, "remove"}); //临界区
            message_queue.cv.notify_all();

            return 0;
        }

};

class MatchCloneFactory : virtual public MatchIfFactory {
    public:
        ~MatchCloneFactory() override = default;
        MatchIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) override
        {
            std::shared_ptr<TSocket> sock = std::dynamic_pointer_cast<TSocket>(connInfo.transport);
            std::cout << "Incoming connection\n";
            std::cout << "\tSocketInfo: "  << sock->getSocketInfo() << "\n";
            std::cout << "\tPeerHost: "    << sock->getPeerHost() << "\n";
            std::cout << "\tPeerAddress: " << sock->getPeerAddress() << "\n";
            std::cout << "\tPeerPort: "    << sock->getPeerPort() << "\n";
            return new MatchHandler;
        }
        void releaseHandler( MatchIf* handler) override {
            delete handler;
        }
};

int main(int argc, char **argv) {
    /*
     * TSimpleServer 只有一个线程处理客户端请求
       int port = 9090;
       ::std::shared_ptr<MatchHandler> handler(new MatchHandler());
       ::std::shared_ptr<TProcessor> processor(new MatchProcessor(handler));
       ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
       ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
       ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

       TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
       */

    // TThreadedServer 每个请求开一个线程处理,并发量高
    TThreadedServer server(
            std::make_shared<MatchProcessorFactory>(std::make_shared<MatchCloneFactory>()),
            std::make_shared<TServerSocket>(9090), //port
            std::make_shared<TBufferedTransportFactory>(),
            std::make_shared<TBinaryProtocolFactory>());

    printf("server running ...\n");

    std::thread matching_thread(consume_task);

    server.serve();
    return 0;
}

